server:
  port: 8081

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cache:
    type: redis
  redis:
    # host: host.docker.internal # 도커로 실행
    # host: localhost # 로컬에서 실행
    host: "i6c107.p.ssafy.io"
    port: 6380


